package com.art241111.imagetodesktop.utils

/**
 * Image List Generator.
 *
 * @author Created by Artem Gerasimov (gerasimov.av.dev@gmail.com).
 */

class PhotoCategoryNames {
    val categories = listOf(
        "Abstract",
        "Blurs",
        "Competition",
        "Craftsmanship",
        "Danger",
        "Exploration",
        "Help",
        "Luxury",
        "Peace",
        "Power",
        "Purity",
        "Security",
        "Sports",
        "Stress",
        "Success",
        "Teamwork",
        "Unique",
        "Backgrounds",
        "Religion",
        "Textures",
        "Love",
        "Seasonal & Holiday",
        "Fun",
        "Colors",
        "Planetarium",
        "Mobile",
        "Aerial",
        "Animals",
        "Pets",
        "Birds",
        "Mammals",
        "Farm",
        "Marine life",
        "Reptiles & Amphibians",
        "Insects",
        "Rodents",
        "Wildlife",
        "Arts & Architecture",
        "Landmarks",
        "Generic architecture",
        "Outdoor",
        "Indoor",
        "Details",
        "Night scenes",
        "Modern buildings",
        "Historic buildings",
        "Home",
        "Work places",
        "Ruins & Ancient",
        "Business",
        "People",
        "Teams",
        "Industries",
        "Computers",
        "Communications",
        "Finance",
        "Still-life",
        "Transportation",
        "Metaphors",
        "Objects",
        "Travel",
        "Editorial",
        "Celebrities",
        "Events",
        "People",
        "Politics",
        "Sports",
        "Weather & Environment",
        "Landmarks",
        "Commercial",
        "Holidays",
        "New Years",
        "Christmas",
        "Thanksgiving",
        "Halloween",
        "Easter",
        "Valentines Day",
        "Mothers Day",
        "Fathers Day",
        "Other",
        "Diwali",
        "Chinese New Year",
        "Ramadan",
        "Mardi Gras",
        "Cinco de Mayo",
        "Hanukkah",
        "IT & C",
        "Networking",
        "Connectivity",
        "Internet",
        "Equipment",
        "Artificial Intelligence",
        "Illustrations & Clipart",
        "Illustrations",
        "3D & Computer generated",
        "Hand drawn & Artistic",
        "Vector",
        "Industries",
        "Banking",
        "Travel",
        "Architecture",
        "Construction",
        "Computers",
        "Healthcare & Medical",
        "Cargo & Shipping",
        "Communications",
        "Legal",
        "Insurance",
        "Power and energy",
        "Transportation",
        "Environment",
        "Manufacturing",
        "Agriculture",
        "Military",
        "Food & Beverages",
        "Entertainment",
        "Education",
        "Sports",
        "Oil and gas",
        "Nature",
        "Generic vegetation",
        "Plants and trees",
        "Details",
        "Mountains",
        "Lakes and rivers",
        "Deserts",
        "Forests",
        "Sea & Ocean",
        "Tropical",
        "Clouds and skies",
        "Sunsets & Sunrises",
        "Waterfalls",
        "Flowers & Gardens",
        "Seasons specific",
        "Fields & Meadows",
        "Food ingredients",
        "Fruits & Vegetables",
        "Geologic and mineral",
        "Landscapes",
        "Water",
        "Objects",
        "Toys",
        "Isolated",
        "Home related",
        "Tools",
        "Clothing & Accessories",
        "Still life",
        "Other",
        "Electronics",
        "Music and sound",
        "Retro",
        "Sports",
        "People",
        "Couples",
        "Women",
        "Men",
        "Families",
        "Children",
        "Teens",
        "Seniors",
        "Diversity",
        "Active",
        "Body parts",
        "Expressions",
        "Workers",
        "Portraits",
        "Nudes",
        "Cosmetic & Makeup",
        "Technology",
        "Telecommunications",
        "Computers",
        "Connections",
        "Retro",
        "Electronics",
        "Other",
        "Science",
        "Travel",
        "Africa",
        "Asia",
        "America",
        "Europe",
        "Australasian",
        "Destination scenics",
        "Cruise",
        "Cuisine",
        "Resorts",
        "Arts & Architecture",
        "Tropical",
        "Currencies",
        "Flags",
        "Antarctica"
    )
}
